### ISSUE TITLE
"We love separating our client-side apps from our server-side API's"

### ISSUE THREAD

**Issue by homeyer** [carrot/we-are-hiring#9]
Hi!

I'm curious your approach to separating your client side code from the server side. 

At Waffle.io we're breaking them apart right now. We've made our API stateless and session-less, each request is authorized by an oauth token. The client side app has server side pieces to handle login, and grants each user an oauth token, but otherwise just hosts client side code.

I'd love to hear what you folks do!

**Comment by jescalan** [comment]
Hey @homeyer!

We have a fairly similar approach. For most of the apps we build here at Carrot, we don't foresee a need for a open public API, since being an agency we mostly work on a variety of smaller projects for companies rather than a single product. So we will typically build a small API that uses sessions, and put it on the same domain as our client-side app, aliased to something like `http://whatever.com/api`, using nginx. The client side app will then be able to use sessions normally since the requests are not cross-domain. This way, we don't need to deal with oauth for what is a fairly straightforward use case. But at the same time, it allows us to build both halves separately, and if we did need to add another platform other than the web, we would still be able to do so without a huge issue because of the separate API.

Other than that, we like building APIs with ruby (sinatra) or node (express), then pairing them up with a front end built with roots, using marionette.js, and hosted on netlify. We're found that this setup gets us the most simplicity and build speed across the stack so far. But we are always experimenting with other new technologies and builds. It benefits us greatly to optimize our workflow for getting up moving quickly, since we are constantly switching between projects and getting new projects set up.

All that said, we face different challenges than product companies do. Our scale is zero to 10,000 in a few minutes, then back to zero within less than a week. We hardly ever deal with long term maintenance or legacy code. We start new projects from scratch all the time. So while we feel pretty confident that for an agency our approach works quite well, product companies should certainly take any advice or preferences from us with a grain of salt.

**Comment by homeyer** [comment]
Awesome, thanks for sharing!

Do you deploy to EC2 and have nginx set up there?

Netlify looks great. We use Angular, and have a fairly robust client side test suite. Do they support the full CI pipeline, or do you use something like Travis or Codeship and have them deploy to Netlify?

**Comment by kylemac** [comment]
@homeyer 

so for client-side: netlify has a webhook interface so you can hook it up really to any CI pipeline. just hit that webhook after your tests pass and it'll trigger a build. (ref: [codeship](https://codeship.com/documentation/integrations/webhooks/), [travis](http://docs.travis-ci.com/user/notifications/#Webhook-notification), [netlify](https://www.netlify.com/docs/webhooks))

alternately, you can link a github (or bitbucket) repo and netlify will watch a particular branch and build your site (with your preferred build tool, like grunt, gulp, roots, ect) every time it sees a commit to that branch. what we'll do is have it hooked up to our `origin/master` and whenever we merge a pull request to master (once the CI/travis tests pass, of course) it'll just trigger a build. you could have an `origin/master` and `origin/develop` for production and staging, respectively. i highly recommend hooking up your site/repo to netlify just to test it out - it's been really great for us.

for server-side hosting, we'll usually spin up a Digital Ocean box for this. most of the time, it's just for nginx and we're using nginx to proxy to our server-side app stuff on heroku. heroku lets us not have to worry so much about provisioning a server and managing all the hassle that comes with that - but there are occasions where we host the actual app on DO too.

what do you guys like using for client-side integration tests?

**Comment by homeyer** [comment]
@kylemac

Nice, we host on heroku right now, although we also ship as docker containers so you can install in your own environment. 

We use [Karma](http://karma-runner.github.io/0.12/index.html) for client side testing. This includes unit testing Angular controllers, and testing directives tied to UI. We use [protractor](https://angular.github.io/protractor/#/) for end to end tests, although only a handful of them (expensive to run, and can be flaky).

**Comment by homeyer** [comment]
Thanks for the great conversation, closing the issue now :).

**Comment by kylemac** [comment]
Likewise. Thanks for stopping by. Happy to chat any time

**Comment by jescalan** [comment]
:two_men_holding_hands:
